apiVersion: v1
kind: Service
metadata:
  name: daemoncontainos-service
spec:
  # type: LoadBalancer
  selector:
    app: daemoncontainos-app
  # ports:
  #   - protocol: TCP
  #     port: 80
  #     targetPort: 5000